---
deprecations: |
  - The following config options are deprecated in favor of a separate
    configuration section ``service_credentials`` introduced to define the
    Trove service user credentials for communication with other OpenStack
    services.

    .. code-block:: ini

        [DEFAULT]
        trove_auth_url
        os_region_name
        nova_proxy_admin_user
        nova_proxy_admin_pass
        nova_proxy_admin_tenant_id
        nova_proxy_admin_tenant_name
        nova_proxy_admin_user_domain_name
        nova_proxy_admin_project_domain_name
